parameters:
    seiffert.crowd.class: Seiffert\CrowdRestBundle\Crowd
    seiffert.crowd.resource.user.class: Seiffert\CrowdRestBundle\Crowd\UserResource
    seiffert.crowd.resource.auth.class: Seiffert\CrowdRestBundle\Crowd\AuthResource
    seiffert.crowd.mapper.user.class: Seiffert\CrowdRestBundle\Crowd\UserMapper
    seiffert.crowd.http_client.class: Guzzle\Http\Client
    seiffert.crowd.http_client.curl_auth_plugin.class: Guzzle\Plugin\CurlAuth\CurlAuthPlugin

services:
    seiffert.crowd:
        class: %seiffert.crowd.class%
        arguments:
            - @seiffert.crowd.resource.user
            - @seiffert.crowd.resource.auth

    seiffert.crowd.resource.user:
        class: %seiffert.crowd.resource.user.class%
        arguments:
            - @seiffert.crowd.http_client
            - @seiffert.crowd.mapper.user

    seiffert.crowd.resource.auth:
        class: %seiffert.crowd.resource.auth.class%
        arguments:
            - @seiffert.crowd.http_client

    seiffert.crowd.mapper.user:
        class: %seiffert.crowd.mapper.user.class%

    seiffert.crowd.http_client:
        class: %seiffert.crowd.http_client.class%
        arguments:
            - %seiffert.crowd.url%
        calls:
            - [ 'addSubscriber', [ @seiffert.crowd.http_client.curl_auth_plugin ]]
            - [ 'setDefaultHeaders', [ { 'Content-Type': 'application/json', 'Accept': 'application/json' } ]]

    seiffert.crowd.http_client.curl_auth_plugin:
        class: %seiffert.crowd.http_client.curl_auth_plugin.class%
        arguments:
            - %seiffert.crowd.application.name%
            - %seiffert.crowd.application.password%
